.gitignore
composer.json

reference: http://cgit.drupalcode.org/drupal/commit/?id=396d9f7cd59a7f9d79117a71692942738653a0fd

OPENEUROPA-772: Create the tag 8.6.0-beta1.

---

composer.json

Reference: http://cgit.drupalcode.org/drupal/commit/?id=43c9fc5f1a8880583628f0d90fa97b938ba3e5d6

OPENEUROPA-772: Back to dev.

---

README.md
composer.json

Related to https://github.com/drupal/core/releases/tag/8.6.0-rc1

OPENEUROPA-1168: Update drupal/core 8.6.0-rc1 on composer.json.

---

composer.json

Reference: http://cgit.drupalcode.org/drupal/commit/?id=beaff9130f698f581af1abead7a6e7eed91211ac

Change drupal/core to 8.6.2.

---

.github/pull_request_template.md
README.md
composer.json

Minor improvements in README file.
- Changed: README.me file.
- Added: github PR template.

OPENEUROPA-1326

---

composer.json

Back to 8.6.x-dev.

---

README.md
composer.json

Add patch for core "Update our Twig code to be ready for Twig 2.x"
- Added: patch "2600154-3-60.patch"

OPENEUROPA-1387: Add patch for core.

---

composer.json

Prepare the release 8.6.5.
- Changed: Version of Drupal/Core on composer.

OPENEUROPA-1560: Prepare the release 8.6.5.

---

composer.json

Back to 8.6.x-dev.
- Changed: Update

OPENEUROPA-1560: Back to 8.6.x-dev.

---

composer.json

Update composer to create the release 8.6.6.
- Changed: Version of Drupal/Core

OPENEUROPA-1560: Update composer to create the release 8.6.6.

---

composer.json

Update composer to create the release 8.6.7.
- Changed: Version of Drupal/Core

OPENEUROPA-1560: Update composer to create the release 8.6.7.

---

composer.json

Back to dev version of Drupal.
- Changed: Drupal version on Composer.

Back to dev.

---

composer.json

Create release 8.6.9.
- Changed: Change Drupal version on Composer.

Update the CHANGELOG.md.

---

composer.json

Update composer for the release 8.6.10.
- Changed: Drupal version on composer.

Release 8.6.10.

---

composer.json

[Insert description here]
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-1718: Rerolling patch from DORG 2600154 issue for 8.6.x-dev.

---

composer.json

Remove patch.

---

composer.json

Create release 8.6.11.

---

composer.json

Create release 8.6.12.

---

.drone.yml
composer.json

Update version of drupal/core to 8.6.13
- Fixed: Version of mikey179/vfsstream.
- Changed: Version of drupal/core.
- Updated: CI drone.

Create release 8.6.13 and update CI drone.

---

README.md
composer.json

Update drupal core version to 8.6.14
- Changed: Update drupal core version to 8.6.14;
- Changed: Patch for DO issue #2599228;
- Changed: Patch for DO issue #2600154 (documentation only).

release-8.6.14

---

README.md
composer.json

Create release 8.7.0-alpha1.
- Changed: patch for https://www.drupal.org/project/drupal/issues/2599228

Create release 8.7.0-alpha1

---

README.md
composer.json

Create release 8.7.0-alpha2.
- Removed: Patch for https://www.drupal.org/project/drupal/issues/2599228

Release 8.7.0-alpha2

---

composer.json

Create release 8.7.0-beta2.
- Removed: patch "https://www.drupal.org/project/drupal/issues/2599228": "https://www.drupal.org/files/issues/2018-10-01/2599228-SQL_error_on_content_creation-78_0.patch"

Create release 8.7.0-beta2

---

composer.json

Change drupal/core to 8.7.0-rc1.

Change drupal/core to 8.7.0-rc1.

---

composer.json

Change drupal/core to 8.6.15.

---

composer.json

Create the release 8.7.0.
- Changed: Version of Drupal.

OPENEUROPA-1766: Release 8.7.0.

---

composer.json

OPENEUROPA-1766: back to dev.

---

composer.json

OPENEUROPA-1766: Release 8.6.16.

---

composer.json

OPENEUROPA-1766: Release 8.7.1.

---

composer.json

Release 8.7.1

---

composer.json

Release 8.7.2.

---

composer.json

OPENEUROPA-1766: Prepare release 8.7.3.

---

composer.json

OPENEUROPA-1766: Prepare release 8.6.17.

---

composer.json

Prepare release 8.7.4.
- Changed: Update composer.json

OPENEUROPA-1766: Prepare release 8.7.4.

---

composer.json

OPENEUROPA-1766: Prepare release 8.7.5.

---

composer.json

OPENEUROPA-1766: Prepare release 8.7.6.

---

composer.json

Prepare 9.0.1 release.
- Added:
- Changed: Prepare 9.0.1 release.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare 9.0.1 release.

---

composer.json

Prepare 8.9.1 release.
- Added:
- Changed:Prepare 8.9.1 release.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare 8.9.1 release.

---

composer.json

Prepare 8.8.8 release
- Added:
- Changed: Prepare 8.8.8 release.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare 8.8.8 release.

---

composer.json

Revert to 8.8.x.
- Added:
- Changed: Revert to 8.8.x.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Revert to 8.8.x.

---

composer.json

Update patch to fix infinite loop issue on kernel tests.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-109: Use new patch for kernel test infinite loop issue.

---

README.md
composer.json

Prepare release 8.9.13
- Added:
- Changed: Update drupal core to 8.9.13
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 8.9.13.
